### ISSUE TITLE
Any chance of getting this extension ported to VSCodium?

### ISSUE THREAD

**Issue by beeburrt** [testdouble/vscode-standard-ruby#3]

**Comment by whysthatso** [comment]
i just downloaded the release from here and starred/watched for new releases.

i'm not absolutely certain, but if i understand correctly, there's no need to port anything, as the ext does not depend on anythgin vscode-specific. it should however be made available on https://open-vsx.org/, but that would be extra work i wouldn't ever demand of the maintainer here.

if some sort of mirroring could be implemented between the ms-marketplace and open-vsx, that would probably make it a bit easier on the maintenance part, and it might be in the interest of the maintainer to control the release over there in order to not be potentially swamped with support requests that might be due to a less-then-optimal run release cycle, again, over there.

i'm very much interested in how this works, so i will try to figure out how it would be the least frictiony way, and will report back here.

**Comment by whysthatso** [comment]
ok, so i think it's mostly a legal matter regarding a publisher agreement with the eclipse foundation described [here](https://www.eclipse.org/legal/open-vsx-registry-faq/#faq-8) and have an account on open-vsx.org.

technically, there is a presumably widely used ci-script [here](https://github.com/open-vsx/publish-extensions) for the publishing process.

so yeah, looks like extra work for the maintainers but it would be greatly appreciated :)

**Comment by whysthatso** [comment]
welp, the extension actually does not work yet for me. when trying "Standard Ruby: Start Language Server" i get an error (command 'standardRuby.start' not found)
The extension itself is present and enabled, i can see settings integrated into the user settings view. Runtime Status says "Not yet activated." For testing i hardcoded the path to standard (/home/me/.asdf/shims/standardrb), Autofix enabled, "always run-wether via bundler or global"

**Comment by whysthatso** [comment]
welp, the extension actually does not work yet for me. when running the command "Standard Ruby: Start Language Server" i get an error (command 'standardRuby.start' not found).

The extension itself is present and enabled, i can see settings integrated into the user settings view. 
Runtime Status says "Not yet activated." 
For testing i: 
  - hardcoded the path to standard (/home/me/.asdf/shims/standardrb)
  - have Autofix enabled
  - set "always run-wether via bundler or global"

Am i missing a dependency maybe?

**Comment by whysthatso** [comment]
uff, this could have been spelled out so much more easily: 

https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace

**Comment by CodingItWrong** [comment]
With VSCodium, instead of using this extension, I've had success with [the "main" Ruby extension](https://open-vsx.org/extension/rebornix/ruby), with the following settings:

```
"ruby.lint": {
    "standard": true
},
"ruby.format": "standard",
```

(May not be necessary, but I'm also using these settings, if it helps:)

```
"ruby.useBundler": true,
"ruby.useLanguageServer": true,
```

**Comment by searls** [comment]
If someone is open to sending a PR that'll submit this extension to the other registry automatically (for example, a GitHub action that listens for new release tags or something), I'd be happy to merge it. But if it's adding extra manual hoops for maintainers to jump through on each release, I'm not comfortable committing to that.
